from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import math

class Rental(models.Model):
    # Link to the registered student
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    
    # Required verification details
    national_id = models.CharField(max_length=20)
    uni_reg_number = models.CharField(max_length=50)
    
    # Timestamps (Auto-generated by system, not user-editable)
    start_time = models.DateTimeField(null=True, blank=True)
    end_time = models.DateTimeField(null=True, blank=True)
    
    # Billing fields
    total_cost = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    is_active = models.BooleanField(default=False)
    is_paid = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.customer.username} - {self.uni_reg_number} ({'Active' if self.is_active else 'Closed'})"

    def calculate_cost(self):
        """
        Calculates the cost based on a 70 per hour rate.
        Calculates to the nearest second for fairness.
        """
        if self.start_time and self.end_time:
            # Calculate the time difference
            duration = self.end_time - self.start_time
            seconds = duration.total_seconds()
            
            # Convert seconds to hours (e.g., 90 mins = 1.5 hours)
            hours = seconds / 3600
            
            # Rate of 70 per hour
            # We use max(hours, 0.02) to ensure a tiny minimum charge (approx 1 min) if stopped instantly
            calculated_amount = hours * 70
            
            self.total_cost = round(max(calculated_amount, 0), 2)
            self.save()

    class Meta:
        verbose_name = "Bike Rental"
        verbose_name_plural = "Bike Rentals"