# Generated by Django 6.0.3 on 2026-03-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'verbose_name': 'Bike Rental', 'verbose_name_plural': 'Bike Rentals'},
        ),
        migrations.AddField(
            model_name='rental',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
