# Generated by Django 6.0.3 on 2026-03-05 07:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_rental_options_rental_is_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_number', models.CharField(help_text='e.g., BK-001', max_length=10, unique=True)),
                ('is_available', models.BooleanField(default=True, help_text='Is the bike currently at the station?')),
                ('needs_maintenance', models.BooleanField(default=False, help_text='Check this to remove bike from public view')),
            ],
        ),
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ['-start_time']},
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='uni_reg_number',
            new_name='registration_number',
        ),
        migrations.AddField(
            model_name='rental',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='rental_photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rental',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rental',
            name='bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.bike'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('total_rides', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
